### ISSUE TITLE
Input Issue

### ISSUE THREAD

**Issue by PadarthiNitheesh** [ccipd/MRQy#32]
MRQy is not accepting the dicom images it is showing no of patients 0

This is the thing i am getting
MRQy is starting....
The number of patients is 0
The input folder is empty or includes unsupported files format!
Skipped the t-SNE and UMAP computation because of insufficient data. The UMAP and t-SNE process need at least 6 input data.
Traceback (most recent call last):
  File "C:\Users\raman\MRQy-master\src\mrqy\QC.py", line 377, in <module>
    df = tsv_to_dataframe(address)
  File "C:\Users\raman\MRQy-master\src\mrqy\QC.py", line 206, in tsv_to_dataframe
    return pd.read_csv(tsvfileaddress, sep='\t', skiprows=2, header=0)
  File "C:\Anaconda\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "C:\Anaconda\lib\site-packages\pandas\io\parsers\readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "C:\Anaconda\lib\site-packages\pandas\io\parsers\readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "C:\Anaconda\lib\site-packages\pandas\io\parsers\readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "C:\Anaconda\lib\site-packages\pandas\io\parsers\readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "C:\Anaconda\lib\site-packages\pandas\io\parsers\c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "C:\Anaconda\lib\site-packages\pandas\io\parsers\base_parser.py", line 222, in _open_handles
    self.handles = get_handle(
  File "C:\Anaconda\lib\site-packages\pandas\io\common.py", line 702, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\raman\\MRQy-master\\src\\mrqy\\UserInterface\\Data\\gbm_raw\\results.tsv'

**Comment by mohsenhariri** [comment]
Resolved.
