### ISSUE TITLE
DLL load failed while importing _remap - module not found

### ISSUE THREAD

**Issue by matteawelch** [ccipd/MRQy#7]
Hi!

While testing whether the code is functional (`python -m mrqy.QC --help`) I have run into a few problems. 

1) The first error was "ModuleNotFoundError: No module named 'skimage' - Subsequently I ran `pipenv install scikit-image `
2) After installing the scikit-image package I received the error: ImportError: DLL load failed while importing _remap: the specified module could not be found. Based on this post: https://github.com/scikit-image/scikit-image/issues/4780 I ran pipenv `install msvc-runtime`, but am still getting the following error:

 ```
PS C:\Users\Mattea\MDACC\MRQy> pipenv install .
Installing ....
Adding mrqy to Pipfile's [packages]...
Installation Succeeded
Installing dependencies from Pipfile.lock (fd82fb)...
  ================================ 1/1 - 00:00:00
PS C:\Users\Mattea\MDACC\MRQy> python -m mrqy.QC --help
Traceback (most recent call last):
  File "C:\Users\Mattea\anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Mattea\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Mattea\.virtualenvs\MRQy-0a-sfUiD\lib\site-packages\mrqy\QC.py", line 11, in <module>
    import mrqy.QCF as QCF ## import QCF
  File "C:\Users\Mattea\.virtualenvs\MRQy-0a-sfUiD\lib\site-packages\mrqy\QCF.py", line 17, in <module>
    from skimage.filters import threshold_otsu
  File "C:\Users\Mattea\.virtualenvs\MRQy-0a-sfUiD\lib\site-packages\skimage\__init__.py", line 127, in <module>
    from .util.dtype import (img_as_float32,
  File "C:\Users\Mattea\.virtualenvs\MRQy-0a-sfUiD\lib\site-packages\skimage\util\__init__.py", line 17, in <module>
    from ._map_array import map_array
  File "C:\Users\Mattea\.virtualenvs\MRQy-0a-sfUiD\lib\site-packages\skimage\util\_map_array.py", line 2, in <module>
    from ._remap import _map_array
ImportError: DLL load failed while importing _remap: The specified module could not be found.

```

Any tips or suggestions would be greatly appreciated!
Thanks, 
Mattea

**Comment by cedrik24** [comment]
Hi,
I have exactly the same problem. If you have found the solution, can share it here?
Thanks :-)

**Comment by satishev** [comment]
@Amir-Reza-Sadri is looking into this, will respond soon.

**Comment by Amir-Reza-Sadri** [comment]
Which version of Python did you use? Please make sure all the prerequisite packages/libraries are up to date. As an alternative, you can try to install MRQy directly without the pip environment which is mentioned [here](https://github.com/ccipd/MRQy).
